# Generated by Django 4.2.5 on 2023-10-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='description',
            new_name='delivery_address',
        ),
    ]
