# Generated by Django 4.2.5 on 2023-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_review'),
        ('cart', '0003_rename_description_purchase_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='devices.device'),
        ),
    ]
