# Generated by Django 4.2.5 on 2023-10-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_purchase_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='devices',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
