# Generated by Django 4.2.5 on 2023-10-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_purchase_cart_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
