# Generated by Django 4.2.5 on 2023-10-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_purchase_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cart',
        ),
    ]
