# Generated by Django 4.2.5 on 2023-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_purchase_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_devices',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
