# Generated by Django 5.0 on 2023-12-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
